version: '1'
services:
  nginx:
    container_name: c-nginx
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./chatRoomWeb:/chatRoomWeb

  app:
    restart: always
    build: .
    working_dir: ./chatRoom
    volumes:
      - ./chatRoom:/chatRoom/chatRoom
      - ./socket:/chatRoom/socket
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    depends_on:
      - nginx
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker