version: '1'
services:
  nginx:
    container_name: c-nginx
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ../chatRoom/dist:/chatRoom/dist

  app:
    restart: always
    build: .
    working_dir: /chatRoom
    volumes:
      - .:/chatRoom
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    depends_on:
      - nginx
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker